export const GnosisChainReceiverV2Abi = [
	{ type: 'constructor', inputs: [] },
	{
		type: 'function',
		stateMutability: 'payable',
		outputs: [],
		name: 'addSecretVoucher',
		inputs: [
			{ type: 'bytes32', name: '_key', internalType: 'bytes32' },
			{ type: 'uint256', name: '_voucherPrice', internalType: 'uint256' },
		],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'changeFaucetAmountPerNewUser',
		inputs: [{ type: 'uint256', name: '_amount', internalType: 'uint256' }],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'changeOwner',
		inputs: [{ type: 'address', name: '_owner', internalType: 'address' }],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'changeVoucherController',
		inputs: [{ type: 'address', name: '_voucherController', internalType: 'address' }],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'claimSecretVoucher',
		inputs: [{ type: 'string', name: '_superSecretCode', internalType: 'string' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'faucetAmountPerNewUser',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'payable',
		outputs: [],
		name: 'fundAddress',
		inputs: [{ type: 'address', name: '_to', internalType: 'address' }],
	},
	{
		type: 'function',
		stateMutability: 'payable',
		outputs: [],
		name: 'fundAddresses',
		inputs: [
			{ type: 'address[]', name: '_tos', internalType: 'address[]' },
			{ type: 'uint256[]', name: '_amounts', internalType: 'uint256[]' },
		],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
		name: 'marketsWhitelist',
		inputs: [{ type: 'address', name: '', internalType: 'address' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'address', name: '', internalType: 'address' }],
		name: 'owner',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'placeBet',
		inputs: [
			{ type: 'address', name: '_market', internalType: 'address' },
			{ type: 'address', name: '_attribution', internalType: 'address' },
			{ type: 'bytes32[]', name: '_results', internalType: 'bytes32[]' },
		],
	},
	{
		type: 'function',
		stateMutability: 'payable',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'placeBets',
		inputs: [
			{ type: 'address', name: '_market', internalType: 'address' },
			{ type: 'address[]', name: '_attributions', internalType: 'address[]' },
			{ type: 'bytes32[][]', name: '_resultsArray', internalType: 'bytes32[][]' },
		],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'removeSecretVouchers',
		inputs: [{ type: 'bytes32[]', name: '_keys', internalType: 'bytes32[]' }],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'removeVouchers',
		inputs: [{ type: 'address[]', name: '_accounts', internalType: 'address[]' }],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'retrieveXDAI',
		inputs: [
			{ type: 'address', name: '_to', internalType: 'address payable' },
			{ type: 'uint256', name: '_amount', internalType: 'uint256' },
		],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [
			{ type: 'uint256', name: 'voucherPrice', internalType: 'uint256' },
			{ type: 'uint256', name: 'value', internalType: 'uint256' },
		],
		name: 'secretVouchers',
		inputs: [{ type: 'bytes32', name: '', internalType: 'bytes32' }],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'transferVoucher',
		inputs: [
			{ type: 'address', name: '_from', internalType: 'address' },
			{ type: 'address', name: '_to', internalType: 'address' },
			{ type: 'uint256', name: '_amount', internalType: 'uint256' },
		],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'voucherBalance',
		inputs: [{ type: 'address', name: '', internalType: 'address' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'address', name: '', internalType: 'address' }],
		name: 'voucherController',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'voucherTotalSupply',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'whitelistMarket',
		inputs: [
			{ type: 'address', name: '_market', internalType: 'address' },
			{ type: 'bool', name: '_whitelist', internalType: 'bool' },
		],
	},
	{ type: 'function', stateMutability: 'nonpayable', outputs: [], name: 'withdrawWXDAI', inputs: [] },
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [{ type: 'bytes', name: '', internalType: 'bytes' }],
		name: 'xReceive',
		inputs: [
			{ type: 'bytes32', name: '_transferId', internalType: 'bytes32' },
			{ type: 'uint256', name: '_amount', internalType: 'uint256' },
			{ type: 'address', name: '_asset', internalType: 'address' },
			{ type: 'address', name: '_originSender', internalType: 'address' },
			{ type: 'uint32', name: '_origin', internalType: 'uint32' },
			{ type: 'bytes', name: '_callData', internalType: 'bytes' },
		],
	},
	{
		type: 'event',
		name: 'FundingReceived',
		inputs: [
			{ type: 'address', name: '_from', indexed: true },
			{ type: 'address', name: '_to', indexed: true },
			{ type: 'uint256', name: '_amount', indexed: false },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'VoucherAmountChanged',
		inputs: [
			{ type: 'address', name: '_account', indexed: true },
			{ type: 'uint256', name: '_newBalance', indexed: false },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'VoucherTransfered',
		inputs: [
			{ type: 'address', name: '_from', indexed: true },
			{ type: 'address', name: '_to', indexed: true },
			{ type: 'uint256', name: '_amount', indexed: false },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'VoucherUsed',
		inputs: [
			{ type: 'address', name: '_player', indexed: true },
			{ type: 'address', name: '_market', indexed: true },
			{ type: 'uint256', name: '_tokenId', indexed: true },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'WhitelistChanged',
		inputs: [
			{ type: 'address', name: '_market', indexed: true },
			{ type: 'bool', name: 'whitelisted', indexed: false },
		],
		anonymous: false,
	},
	{ type: 'receive' },
] as const
