export const MarketAbi = [
	{ type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'CLEAN_TOKEN_ID',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'DIVISOR',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'approve',
		inputs: [
			{ type: 'address', name: 'to', internalType: 'address' },
			{
				type: 'uint256',
				name: 'tokenId',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'attributionBalance',
		inputs: [{ type: 'address', name: '', internalType: 'address' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'balanceOf',
		inputs: [{ type: 'address', name: 'owner', internalType: 'address' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'address', name: '', internalType: 'address' }],
		name: 'betNFTDescriptor',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: 'count', internalType: 'uint256' }],
		name: 'bets',
		inputs: [{ type: 'bytes32', name: '', internalType: 'bytes32' }],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'claimRewards',
		inputs: [
			{ type: 'uint256', name: '_rankIndex', internalType: 'uint256' },
			{
				type: 'uint256',
				name: '_firstSharedIndex',
				internalType: 'uint256',
			},
			{ type: 'uint256', name: '_lastSharedIndex', internalType: 'uint256' },
		],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'closingTime',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'distributeRemainingPrizes',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'payable',
		outputs: [],
		name: 'fundMarket',
		inputs: [{ type: 'string', name: '_message', internalType: 'string' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'address', name: '', internalType: 'address' }],
		name: 'getApproved',
		inputs: [{ type: 'uint256', name: 'tokenId', internalType: 'uint256' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'bytes32[]', name: '', internalType: 'bytes32[]' }],
		name: 'getPredictions',
		inputs: [{ type: 'uint256', name: '_tokenID', internalType: 'uint256' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256[]', name: '', internalType: 'uint256[]' }],
		name: 'getPrizes',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: 'totalPoints', internalType: 'uint256' }],
		name: 'getScore',
		inputs: [{ type: 'uint256', name: '_tokenID', internalType: 'uint256' }],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'initialize',
		inputs: [
			{
				type: 'tuple',
				name: '_marketInfo',
				internalType: 'struct Market.MarketInfo',
				components: [
					{ type: 'uint16' },
					{ type: 'uint16' },
					{ type: 'address' },
					{ type: 'string' },
					{ type: 'string' },
				],
			},
			{ type: 'address', name: '_nftDescriptor', internalType: 'address' },
			{
				type: 'address',
				name: '_realityETH',
				internalType: 'address',
			},
			{ type: 'uint256', name: '_closingTime', internalType: 'uint256' },
			{
				type: 'uint256',
				name: '_price',
				internalType: 'uint256',
			},
			{ type: 'uint256', name: '_submissionTimeout', internalType: 'uint256' },
			{
				type: 'bytes32[]',
				name: '_questionIDs',
				internalType: 'bytes32[]',
			},
			{ type: 'uint16[]', name: '_prizeWeights', internalType: 'uint16[]' },
		],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
		name: 'initialized',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
		name: 'isApprovedForAll',
		inputs: [
			{ type: 'address', name: 'owner', internalType: 'address' },
			{
				type: 'address',
				name: 'operator',
				internalType: 'address',
			},
		],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
		name: 'isRanked',
		inputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'managementReward',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [
			{ type: 'uint16', name: 'fee', internalType: 'uint16' },
			{
				type: 'uint16',
				name: 'royaltyFee',
				internalType: 'uint16',
			},
			{ type: 'address', name: 'manager', internalType: 'address payable' },
			{
				type: 'string',
				name: 'marketName',
				internalType: 'string',
			},
			{ type: 'string', name: 'marketSymbol', internalType: 'string' },
		],
		name: 'marketInfo',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'string', name: '', internalType: 'string' }],
		name: 'name',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'nextTokenID',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'numberOfQuestions',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'address', name: '', internalType: 'address' }],
		name: 'ownerOf',
		inputs: [{ type: 'uint256', name: 'tokenId', internalType: 'uint256' }],
	},
	{
		type: 'function',
		stateMutability: 'payable',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'placeBet',
		inputs: [
			{ type: 'address', name: '_attribution', internalType: 'address' },
			{
				type: 'bytes32[]',
				name: '_results',
				internalType: 'bytes32[]',
			},
		],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'price',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint16', name: '', internalType: 'uint16' }],
		name: 'prizeWeights',
		inputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'bytes32', name: '', internalType: 'bytes32' }],
		name: 'questionIDs',
		inputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'bytes32', name: '', internalType: 'bytes32' }],
		name: 'questionsHash',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [
			{ type: 'uint256', name: 'tokenID', internalType: 'uint256' },
			{
				type: 'uint248',
				name: 'points',
				internalType: 'uint248',
			},
			{ type: 'bool', name: 'claimed', internalType: 'bool' },
		],
		name: 'ranking',
		inputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'address', name: '', internalType: 'contract RealityETH_v3_0' }],
		name: 'realitio',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'registerAll',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'registerAvailabilityOfResults',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'registerPoints',
		inputs: [
			{ type: 'uint256', name: '_tokenID', internalType: 'uint256' },
			{
				type: 'uint256',
				name: '_rankIndex',
				internalType: 'uint256',
			},
			{ type: 'uint256', name: '_duplicates', internalType: 'uint256' },
		],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'reimbursePlayer',
		inputs: [{ type: 'uint256', name: '_tokenID', internalType: 'uint256' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'resultSubmissionPeriodStart',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [
			{ type: 'address', name: 'receiver', internalType: 'address' },
			{
				type: 'uint256',
				name: 'royaltyAmount',
				internalType: 'uint256',
			},
		],
		name: 'royaltyInfo',
		inputs: [
			{ type: 'uint256', name: '', internalType: 'uint256' },
			{
				type: 'uint256',
				name: '_salePrice',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'safeTransferFrom',
		inputs: [
			{ type: 'address', name: 'from', internalType: 'address' },
			{
				type: 'address',
				name: 'to',
				internalType: 'address',
			},
			{ type: 'uint256', name: 'tokenId', internalType: 'uint256' },
		],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'safeTransferFrom',
		inputs: [
			{ type: 'address', name: 'from', internalType: 'address' },
			{
				type: 'address',
				name: 'to',
				internalType: 'address',
			},
			{ type: 'uint256', name: 'tokenId', internalType: 'uint256' },
			{
				type: 'bytes',
				name: '_data',
				internalType: 'bytes',
			},
		],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'setApprovalForAll',
		inputs: [
			{ type: 'address', name: 'operator', internalType: 'address' },
			{
				type: 'bool',
				name: 'approved',
				internalType: 'bool',
			},
		],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'submissionTimeout',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
		name: 'supportsInterface',
		inputs: [{ type: 'bytes4', name: 'interfaceId', internalType: 'bytes4' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'string', name: '', internalType: 'string' }],
		name: 'symbol',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'bytes32', name: '', internalType: 'bytes32' }],
		name: 'tokenIDtoTokenHash',
		inputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'string', name: '', internalType: 'string' }],
		name: 'tokenURI',
		inputs: [{ type: 'uint256', name: 'tokenId', internalType: 'uint256' }],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'totalAttributions',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'view',
		outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
		name: 'totalPrize',
		inputs: [],
	},
	{
		type: 'function',
		stateMutability: 'nonpayable',
		outputs: [],
		name: 'transferFrom',
		inputs: [
			{ type: 'address', name: 'from', internalType: 'address' },
			{
				type: 'address',
				name: 'to',
				internalType: 'address',
			},
			{ type: 'uint256', name: 'tokenId', internalType: 'uint256' },
		],
	},
	{
		type: 'event',
		name: 'Approval',
		inputs: [
			{ type: 'address', name: 'owner', indexed: true },
			{
				type: 'address',
				name: 'approved',
				indexed: true,
			},
			{ type: 'uint256', name: 'tokenId', indexed: true },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'ApprovalForAll',
		inputs: [
			{ type: 'address', name: 'owner', indexed: true },
			{
				type: 'address',
				name: 'operator',
				indexed: true,
			},
			{ type: 'bool', name: 'approved', indexed: false },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Attribution',
		inputs: [{ type: 'address', name: '_provider', indexed: true }],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'BetReward',
		inputs: [
			{ type: 'uint256', name: '_tokenID', indexed: true },
			{
				type: 'uint256',
				name: '_reward',
				indexed: false,
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'FundingReceived',
		inputs: [
			{ type: 'address', name: '_funder', indexed: true },
			{
				type: 'uint256',
				name: '_amount',
				indexed: false,
			},
			{ type: 'string', name: '_message', indexed: false },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'ManagementReward',
		inputs: [
			{ type: 'address', name: '_manager', indexed: false },
			{
				type: 'uint256',
				name: '_managementReward',
				indexed: false,
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'PlaceBet',
		inputs: [
			{ type: 'address', name: '_player', indexed: true },
			{
				type: 'uint256',
				name: 'tokenID',
				indexed: true,
			},
			{ type: 'bytes32', name: '_tokenHash', indexed: true },
			{
				type: 'bytes32[]',
				name: '_predictions',
				indexed: false,
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Prizes',
		inputs: [{ type: 'uint16[]', name: '_prizes', indexed: false }],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'QuestionsRegistered',
		inputs: [{ type: 'bytes32[]', name: '_questionIDs', indexed: false }],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'RankingUpdated',
		inputs: [
			{ type: 'uint256', name: '_tokenID', indexed: true },
			{
				type: 'uint256',
				name: '_points',
				indexed: false,
			},
			{ type: 'uint256', name: '_index', indexed: false },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Transfer',
		inputs: [
			{ type: 'address', name: 'from', indexed: true },
			{
				type: 'address',
				name: 'to',
				indexed: true,
			},
			{ type: 'uint256', name: 'tokenId', indexed: true },
		],
		anonymous: false,
	},
] as const
